### ISSUE TITLE
Android 10 Support Discussion

### ISSUE THREAD

**Issue by animegamer4422** [overzero-git/DriveDroid-fix-Magisk-module#1]
I'd like to know why android 11+ is only supported 
i looked into the scriot and it checks for api level 30 and as usual i edited it to 29 which is what my device is on 
the module installed but yep the DriveDroid didn't worked
so i wanted to know if i can do something to contribute and add the support for android 10 

#Device Details
Manufacturer : Samsung
Model : A7 (2018)
Codename : a7y18lte

Kernel : Stock
OS : Stock samsung ONEUI heavily debloated (even removed gapps)
DriveDroid : The module provided apk was installed

**Comment by overzero-git** [comment]
> I'd like to know why android 11+ is only supported i looked into the scriot and it checks for api level 30 and as usual i edited it to 29 which is what my device is on the module installed but yep the DriveDroid didn't worked so i wanted to know if i can do something to contribute and add the support for android 10
> 
> #Device Details Manufacturer : Samsung Model : A7 (2018) Codename : a7y18lte
> 
> Kernel : Stock OS : Stock samsung ONEUI heavily debloated (even removed gapps) DriveDroid : The module provided apk was installed

Hello! As I researched in Android 10 some parts of USB Host function applied in /system and other in /vendor. Due to unknown reason dynamic changes applies not in all times/devices. I was unable to solve it, so I set that api limitation. In this case you have two ways: you can make it working by editing this script for you (please note, that Samsung stock firmware VERY capricious, and can be broken by random thing) or you can use custom AOSP-based firmware (like Lineage OS, Pixel Expirience etc.). Please also note that Android Auto/ADB/OTG functions can be broken too, and in some different cases it will cause firmware reflash for solution.

**Comment by animegamer4422** [comment]
well i switched to TrebleDroid Android 13 and This is not even the issue right now
the magisk is broken on it 
https://github.com/TrebleDroid/treble_experimentations/issues/44

so yeah priorities shifted
BTW Thanks for your work on this

**Comment by overzero-git** [comment]
> well i switched to TrebleDroid Android 13 and This is not even the issue right now the magisk is broken on it [TrebleDroid/treble_experimentations#44](https://github.com/TrebleDroid/treble_experimentations/issues/44)
> 
> so yeah priorities shifted BTW Thanks for your work on this

Well, I will keep waiting for your feedback then!

**Comment by animegamer4422** [comment]
sure there has been a new gsi image released 5 hours ago i'll test it and see if it works
Thanks

**Comment by animegamer4422** [comment]
Nope that didn't worked
i'll keep you informed in case i can get magisk working again

**Comment by animegamer4422** [comment]
also you should add your amazing magisk module to some popular repo's
like 
https://github.com/ya0211/magisk-modules-alt-repo/

**Comment by overzero-git** [comment]
> Nope that didn't worked i'll keep you informed in case i can get magisk working again

Hello. Anything works on your device?

**Comment by animegamer4422** [comment]
it has been some time since i fiddled with the phone , i was just looking into modifying the script to make it compatible with my android 10 stock oneui 2.0 rom 

the main differences seem to be that the function is called mtp.0 and not mass_storage.0

**Comment by overzero-git** [comment]
> it has been some time since i fiddled with the phone , i was just looking into modifying the script to make it compatible with my android 10 stock oneui 2.0 rom
> 
> the main differences seem to be that the function is called mtp.0 and not mass_storage.0

Thank you for feedback, I'l try to add this modification to the module.
